### ISSUE TITLE
Cannot run Msiler

### ISSUE THREAD

**Issue by miker1423** [segrived/Msiler#41]
I installed the extension but nothing happens, just show the instructions to how to run it, I already have open a solution, and built the project but nothing happend... some help please

**Comment by segrived** [comment]
Hi. You opened Msiler window from Tools menu, but content are not displayed after solution build, right?

**Comment by miker1423** [comment]
yes, I finally made it work but after restarting several times VS, even if I opened it fresh it had trouble getting the solution and getting the builds although the symbols already existed
