### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by segrived** [segrived/Msiler#42]

**Comment by sebas77** [comment]
has this been done? I really would like to use it again.

**Comment by segrived** [comment]
I make some changes for VS2017 support, please try [this version](https://ci.appveyor.com/project/segrived/msiler/build/artifacts). This build right now has some problems, for example it will not work with new style csproj projects, maybe some other bugs. I will try to fix most annoying bugs in short time.

**Comment by segrived** [comment]
Should work with any projects after fix, feel free to try latest version from appveyor.

**Comment by sebas77** [comment]
It works but the follow code option seems not.

**Comment by segrived** [comment]
Hmm, it's strange, follow mode works fine for me. Can you give me minimal example, where follow mode do not work?

**Comment by segrived** [comment]
Msiler for Visual Studio 2017 [was published in Marketplace](https://marketplace.visualstudio.com/items?itemName=segrived.msiler2017), so I will close this issue. If follow mode didn't work for you at this time, please create issue with minimal example to reproduce this problem.
