### ISSUE TITLE
.NET core

### ISSUE THREAD

**Issue by AceHack** [segrived/Msiler#49]
Does this work with .NET core?  I just keep getting the instruction in the msiler window and nothing else.  Thanks.

**Comment by AceHack** [comment]
I found the problem, it's when the window is set to auto hide in VS, then it does not working and nothing happens on rebuild.  If the windows is not set to auto hide then things work.  This is VS2017 latest preview.

**Comment by segrived** [comment]
Please try to disable "Update listing only if toolbox is visible" option in plugin settings

**Comment by segrived** [comment]
Please reopen this issue if you still has this problem.
